### ISSUE TITLE
Installing percolate intercom without id in Meteor.settings breaks the app

### ISSUE THREAD

**Issue by sathishc** [percolatestudio/meteor-intercom#16]
![screen shot 2015-09-19 at 11 05 38 pm](https://cloud.githubusercontent.com/assets/507537/9977387/91a1d678-5f23-11e5-8f3f-4c533fc79bdb.png)

Would it be good if exception thrown and app continues to run without Intercom integration?

**Comment by gsuess** [comment]
+1 Not every deployment should need to have an intercom instance configured to run the app once this package is installed. 

The settings should be optional IMO.

**Comment by zol** [comment]
I will accept a PR for otherwise I'll tackle it in a future round of development.

**Comment by zol** [comment]
I've added a warning. Looking at the code more closely, it's impractical to do anything else as the intercom snippet itself uses the id.
